
apiVersion: v1
kind: Namespace
metadata:
  name: financial-dev
---
apiVersion: v1
kind: Service
metadata:
  name: fin-bil-dev-api-svc
  namespace: financial-dev
  labels:
    app: fin-bil-dev
    tier: api
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: fin-bil-dev
    tier: app
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-bil-dev-api-dep
  namespace: financial-dev  
  labels:
    app: fin-bil-dev
    tier: app
    version: v1
spec:
  selector:
    matchLabels:
      app: fin-bil-dev
      tier: app
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: fin-bil-dev
        tier: app
        version: v1
    spec:
      containers:
        - name: bil-api
          image: finbillapi:dev
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://localhost:27017"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            httpGet:
              path: /swagger/index.html
              port: 80
          resources:
            requests:
              cpu: 25m
              memory: 200Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%